/*
 * Unsent API
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.unsent.types;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.unsent.JSON;

/**
 * CreateCampaign200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-07T19:49:52.238598+06:00[Asia/Dhaka]", comments = "Generator version: 7.18.0")
public class CreateCampaign200Response {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  @javax.annotation.Nonnull
  private String from;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nonnull
  private String subject;

  public static final String SERIALIZED_NAME_PREVIEW_TEXT = "previewText";
  @SerializedName(SERIALIZED_NAME_PREVIEW_TEXT)
  @javax.annotation.Nullable
  private String previewText;

  public static final String SERIALIZED_NAME_CONTACT_BOOK_ID = "contactBookId";
  @SerializedName(SERIALIZED_NAME_CONTACT_BOOK_ID)
  @javax.annotation.Nullable
  private String contactBookId;

  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nullable
  private String html;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nullable
  private String content;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_SCHEDULED_AT = "scheduledAt";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime scheduledAt;

  public static final String SERIALIZED_NAME_BATCH_SIZE = "batchSize";
  @SerializedName(SERIALIZED_NAME_BATCH_SIZE)
  @javax.annotation.Nonnull
  private Integer batchSize;

  public static final String SERIALIZED_NAME_BATCH_WINDOW_MINUTES = "batchWindowMinutes";
  @SerializedName(SERIALIZED_NAME_BATCH_WINDOW_MINUTES)
  @javax.annotation.Nonnull
  private Integer batchWindowMinutes;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nonnull
  private Integer total;

  public static final String SERIALIZED_NAME_SENT = "sent";
  @SerializedName(SERIALIZED_NAME_SENT)
  @javax.annotation.Nonnull
  private Integer sent;

  public static final String SERIALIZED_NAME_DELIVERED = "delivered";
  @SerializedName(SERIALIZED_NAME_DELIVERED)
  @javax.annotation.Nonnull
  private Integer delivered;

  public static final String SERIALIZED_NAME_OPENED = "opened";
  @SerializedName(SERIALIZED_NAME_OPENED)
  @javax.annotation.Nonnull
  private Integer opened;

  public static final String SERIALIZED_NAME_CLICKED = "clicked";
  @SerializedName(SERIALIZED_NAME_CLICKED)
  @javax.annotation.Nonnull
  private Integer clicked;

  public static final String SERIALIZED_NAME_UNSUBSCRIBED = "unsubscribed";
  @SerializedName(SERIALIZED_NAME_UNSUBSCRIBED)
  @javax.annotation.Nonnull
  private Integer unsubscribed;

  public static final String SERIALIZED_NAME_BOUNCED = "bounced";
  @SerializedName(SERIALIZED_NAME_BOUNCED)
  @javax.annotation.Nonnull
  private Integer bounced;

  public static final String SERIALIZED_NAME_HARD_BOUNCED = "hardBounced";
  @SerializedName(SERIALIZED_NAME_HARD_BOUNCED)
  @javax.annotation.Nonnull
  private Integer hardBounced;

  public static final String SERIALIZED_NAME_COMPLAINED = "complained";
  @SerializedName(SERIALIZED_NAME_COMPLAINED)
  @javax.annotation.Nonnull
  private Integer complained;

  public static final String SERIALIZED_NAME_REPLY_TO = "replyTo";
  @SerializedName(SERIALIZED_NAME_REPLY_TO)
  @javax.annotation.Nonnull
  private List<String> replyTo = new ArrayList<>();

  public static final String SERIALIZED_NAME_CC = "cc";
  @SerializedName(SERIALIZED_NAME_CC)
  @javax.annotation.Nonnull
  private List<String> cc = new ArrayList<>();

  public static final String SERIALIZED_NAME_BCC = "bcc";
  @SerializedName(SERIALIZED_NAME_BCC)
  @javax.annotation.Nonnull
  private List<String> bcc = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public CreateCampaign200Response() {
  }

  public CreateCampaign200Response id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public CreateCampaign200Response name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateCampaign200Response from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  public String getFrom() {
    return from;
  }

  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  public CreateCampaign200Response subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nonnull
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public CreateCampaign200Response previewText(@javax.annotation.Nullable String previewText) {
    this.previewText = previewText;
    return this;
  }

  /**
   * Get previewText
   * @return previewText
   */
  @javax.annotation.Nullable
  public String getPreviewText() {
    return previewText;
  }

  public void setPreviewText(@javax.annotation.Nullable String previewText) {
    this.previewText = previewText;
  }


  public CreateCampaign200Response contactBookId(@javax.annotation.Nullable String contactBookId) {
    this.contactBookId = contactBookId;
    return this;
  }

  /**
   * Get contactBookId
   * @return contactBookId
   */
  @javax.annotation.Nullable
  public String getContactBookId() {
    return contactBookId;
  }

  public void setContactBookId(@javax.annotation.Nullable String contactBookId) {
    this.contactBookId = contactBookId;
  }


  public CreateCampaign200Response html(@javax.annotation.Nullable String html) {
    this.html = html;
    return this;
  }

  /**
   * Get html
   * @return html
   */
  @javax.annotation.Nullable
  public String getHtml() {
    return html;
  }

  public void setHtml(@javax.annotation.Nullable String html) {
    this.html = html;
  }


  public CreateCampaign200Response content(@javax.annotation.Nullable String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  public String getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }


  public CreateCampaign200Response status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public CreateCampaign200Response scheduledAt(@javax.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
    return this;
  }

  /**
   * Get scheduledAt
   * @return scheduledAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getScheduledAt() {
    return scheduledAt;
  }

  public void setScheduledAt(@javax.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  public CreateCampaign200Response batchSize(@javax.annotation.Nonnull Integer batchSize) {
    this.batchSize = batchSize;
    return this;
  }

  /**
   * Get batchSize
   * @return batchSize
   */
  @javax.annotation.Nonnull
  public Integer getBatchSize() {
    return batchSize;
  }

  public void setBatchSize(@javax.annotation.Nonnull Integer batchSize) {
    this.batchSize = batchSize;
  }


  public CreateCampaign200Response batchWindowMinutes(@javax.annotation.Nonnull Integer batchWindowMinutes) {
    this.batchWindowMinutes = batchWindowMinutes;
    return this;
  }

  /**
   * Get batchWindowMinutes
   * @return batchWindowMinutes
   */
  @javax.annotation.Nonnull
  public Integer getBatchWindowMinutes() {
    return batchWindowMinutes;
  }

  public void setBatchWindowMinutes(@javax.annotation.Nonnull Integer batchWindowMinutes) {
    this.batchWindowMinutes = batchWindowMinutes;
  }


  public CreateCampaign200Response total(@javax.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nonnull
  public Integer getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nonnull Integer total) {
    this.total = total;
  }


  public CreateCampaign200Response sent(@javax.annotation.Nonnull Integer sent) {
    this.sent = sent;
    return this;
  }

  /**
   * Get sent
   * @return sent
   */
  @javax.annotation.Nonnull
  public Integer getSent() {
    return sent;
  }

  public void setSent(@javax.annotation.Nonnull Integer sent) {
    this.sent = sent;
  }


  public CreateCampaign200Response delivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
    return this;
  }

  /**
   * Get delivered
   * @return delivered
   */
  @javax.annotation.Nonnull
  public Integer getDelivered() {
    return delivered;
  }

  public void setDelivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
  }


  public CreateCampaign200Response opened(@javax.annotation.Nonnull Integer opened) {
    this.opened = opened;
    return this;
  }

  /**
   * Get opened
   * @return opened
   */
  @javax.annotation.Nonnull
  public Integer getOpened() {
    return opened;
  }

  public void setOpened(@javax.annotation.Nonnull Integer opened) {
    this.opened = opened;
  }


  public CreateCampaign200Response clicked(@javax.annotation.Nonnull Integer clicked) {
    this.clicked = clicked;
    return this;
  }

  /**
   * Get clicked
   * @return clicked
   */
  @javax.annotation.Nonnull
  public Integer getClicked() {
    return clicked;
  }

  public void setClicked(@javax.annotation.Nonnull Integer clicked) {
    this.clicked = clicked;
  }


  public CreateCampaign200Response unsubscribed(@javax.annotation.Nonnull Integer unsubscribed) {
    this.unsubscribed = unsubscribed;
    return this;
  }

  /**
   * Get unsubscribed
   * @return unsubscribed
   */
  @javax.annotation.Nonnull
  public Integer getUnsubscribed() {
    return unsubscribed;
  }

  public void setUnsubscribed(@javax.annotation.Nonnull Integer unsubscribed) {
    this.unsubscribed = unsubscribed;
  }


  public CreateCampaign200Response bounced(@javax.annotation.Nonnull Integer bounced) {
    this.bounced = bounced;
    return this;
  }

  /**
   * Get bounced
   * @return bounced
   */
  @javax.annotation.Nonnull
  public Integer getBounced() {
    return bounced;
  }

  public void setBounced(@javax.annotation.Nonnull Integer bounced) {
    this.bounced = bounced;
  }


  public CreateCampaign200Response hardBounced(@javax.annotation.Nonnull Integer hardBounced) {
    this.hardBounced = hardBounced;
    return this;
  }

  /**
   * Get hardBounced
   * @return hardBounced
   */
  @javax.annotation.Nonnull
  public Integer getHardBounced() {
    return hardBounced;
  }

  public void setHardBounced(@javax.annotation.Nonnull Integer hardBounced) {
    this.hardBounced = hardBounced;
  }


  public CreateCampaign200Response complained(@javax.annotation.Nonnull Integer complained) {
    this.complained = complained;
    return this;
  }

  /**
   * Get complained
   * @return complained
   */
  @javax.annotation.Nonnull
  public Integer getComplained() {
    return complained;
  }

  public void setComplained(@javax.annotation.Nonnull Integer complained) {
    this.complained = complained;
  }


  public CreateCampaign200Response replyTo(@javax.annotation.Nonnull List<String> replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  public CreateCampaign200Response addReplyToItem(String replyToItem) {
    if (this.replyTo == null) {
      this.replyTo = new ArrayList<>();
    }
    this.replyTo.add(replyToItem);
    return this;
  }

  /**
   * Get replyTo
   * @return replyTo
   */
  @javax.annotation.Nonnull
  public List<String> getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(@javax.annotation.Nonnull List<String> replyTo) {
    this.replyTo = replyTo;
  }


  public CreateCampaign200Response cc(@javax.annotation.Nonnull List<String> cc) {
    this.cc = cc;
    return this;
  }

  public CreateCampaign200Response addCcItem(String ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<>();
    }
    this.cc.add(ccItem);
    return this;
  }

  /**
   * Get cc
   * @return cc
   */
  @javax.annotation.Nonnull
  public List<String> getCc() {
    return cc;
  }

  public void setCc(@javax.annotation.Nonnull List<String> cc) {
    this.cc = cc;
  }


  public CreateCampaign200Response bcc(@javax.annotation.Nonnull List<String> bcc) {
    this.bcc = bcc;
    return this;
  }

  public CreateCampaign200Response addBccItem(String bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<>();
    }
    this.bcc.add(bccItem);
    return this;
  }

  /**
   * Get bcc
   * @return bcc
   */
  @javax.annotation.Nonnull
  public List<String> getBcc() {
    return bcc;
  }

  public void setBcc(@javax.annotation.Nonnull List<String> bcc) {
    this.bcc = bcc;
  }


  public CreateCampaign200Response createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CreateCampaign200Response updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCampaign200Response createCampaign200Response = (CreateCampaign200Response) o;
    return Objects.equals(this.id, createCampaign200Response.id) &&
        Objects.equals(this.name, createCampaign200Response.name) &&
        Objects.equals(this.from, createCampaign200Response.from) &&
        Objects.equals(this.subject, createCampaign200Response.subject) &&
        Objects.equals(this.previewText, createCampaign200Response.previewText) &&
        Objects.equals(this.contactBookId, createCampaign200Response.contactBookId) &&
        Objects.equals(this.html, createCampaign200Response.html) &&
        Objects.equals(this.content, createCampaign200Response.content) &&
        Objects.equals(this.status, createCampaign200Response.status) &&
        Objects.equals(this.scheduledAt, createCampaign200Response.scheduledAt) &&
        Objects.equals(this.batchSize, createCampaign200Response.batchSize) &&
        Objects.equals(this.batchWindowMinutes, createCampaign200Response.batchWindowMinutes) &&
        Objects.equals(this.total, createCampaign200Response.total) &&
        Objects.equals(this.sent, createCampaign200Response.sent) &&
        Objects.equals(this.delivered, createCampaign200Response.delivered) &&
        Objects.equals(this.opened, createCampaign200Response.opened) &&
        Objects.equals(this.clicked, createCampaign200Response.clicked) &&
        Objects.equals(this.unsubscribed, createCampaign200Response.unsubscribed) &&
        Objects.equals(this.bounced, createCampaign200Response.bounced) &&
        Objects.equals(this.hardBounced, createCampaign200Response.hardBounced) &&
        Objects.equals(this.complained, createCampaign200Response.complained) &&
        Objects.equals(this.replyTo, createCampaign200Response.replyTo) &&
        Objects.equals(this.cc, createCampaign200Response.cc) &&
        Objects.equals(this.bcc, createCampaign200Response.bcc) &&
        Objects.equals(this.createdAt, createCampaign200Response.createdAt) &&
        Objects.equals(this.updatedAt, createCampaign200Response.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, from, subject, previewText, contactBookId, html, content, status, scheduledAt, batchSize, batchWindowMinutes, total, sent, delivered, opened, clicked, unsubscribed, bounced, hardBounced, complained, replyTo, cc, bcc, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCampaign200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    previewText: ").append(toIndentedString(previewText)).append("\n");
    sb.append("    contactBookId: ").append(toIndentedString(contactBookId)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("    batchSize: ").append(toIndentedString(batchSize)).append("\n");
    sb.append("    batchWindowMinutes: ").append(toIndentedString(batchWindowMinutes)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    sent: ").append(toIndentedString(sent)).append("\n");
    sb.append("    delivered: ").append(toIndentedString(delivered)).append("\n");
    sb.append("    opened: ").append(toIndentedString(opened)).append("\n");
    sb.append("    clicked: ").append(toIndentedString(clicked)).append("\n");
    sb.append("    unsubscribed: ").append(toIndentedString(unsubscribed)).append("\n");
    sb.append("    bounced: ").append(toIndentedString(bounced)).append("\n");
    sb.append("    hardBounced: ").append(toIndentedString(hardBounced)).append("\n");
    sb.append("    complained: ").append(toIndentedString(complained)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "from", "subject", "previewText", "contactBookId", "html", "content", "status", "scheduledAt", "batchSize", "batchWindowMinutes", "total", "sent", "delivered", "opened", "clicked", "unsubscribed", "bounced", "hardBounced", "complained", "replyTo", "cc", "bcc", "createdAt", "updatedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "from", "subject", "previewText", "contactBookId", "html", "content", "status", "scheduledAt", "batchSize", "batchWindowMinutes", "total", "sent", "delivered", "opened", "clicked", "unsubscribed", "bounced", "hardBounced", "complained", "replyTo", "cc", "bcc", "createdAt", "updatedAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateCampaign200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateCampaign200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateCampaign200Response is not found in the empty JSON string", CreateCampaign200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateCampaign200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateCampaign200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateCampaign200Response.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      if (!jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("previewText") != null && !jsonObj.get("previewText").isJsonNull()) && !jsonObj.get("previewText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `previewText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("previewText").toString()));
      }
      if ((jsonObj.get("contactBookId") != null && !jsonObj.get("contactBookId").isJsonNull()) && !jsonObj.get("contactBookId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contactBookId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactBookId").toString()));
      }
      if ((jsonObj.get("html") != null && !jsonObj.get("html").isJsonNull()) && !jsonObj.get("html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html").toString()));
      }
      if ((jsonObj.get("content") != null && !jsonObj.get("content").isJsonNull()) && !jsonObj.get("content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("replyTo") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("replyTo").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `replyTo` to be an array in the JSON string but got `%s`", jsonObj.get("replyTo").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("cc") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("cc").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cc` to be an array in the JSON string but got `%s`", jsonObj.get("cc").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("bcc") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("bcc").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bcc` to be an array in the JSON string but got `%s`", jsonObj.get("bcc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateCampaign200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateCampaign200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateCampaign200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateCampaign200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateCampaign200Response>() {
           @Override
           public void write(JsonWriter out, CreateCampaign200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateCampaign200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateCampaign200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateCampaign200Response
   * @throws IOException if the JSON string is invalid with respect to CreateCampaign200Response
   */
  public static CreateCampaign200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateCampaign200Response.class);
  }

  /**
   * Convert an instance of CreateCampaign200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

