/*
 * Unsent API
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.unsent.types;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.unsent.types.CreateCampaignRequestReplyTo;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.unsent.JSON;

/**
 * CreateCampaignRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-07T19:49:52.238598+06:00[Asia/Dhaka]", comments = "Generator version: 7.18.0")
public class CreateCampaignRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  @javax.annotation.Nonnull
  private String from;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nonnull
  private String subject;

  public static final String SERIALIZED_NAME_PREVIEW_TEXT = "previewText";
  @SerializedName(SERIALIZED_NAME_PREVIEW_TEXT)
  @javax.annotation.Nullable
  private String previewText;

  public static final String SERIALIZED_NAME_CONTACT_BOOK_ID = "contactBookId";
  @SerializedName(SERIALIZED_NAME_CONTACT_BOOK_ID)
  @javax.annotation.Nonnull
  private String contactBookId;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nullable
  private String content;

  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nullable
  private String html;

  public static final String SERIALIZED_NAME_REPLY_TO = "replyTo";
  @SerializedName(SERIALIZED_NAME_REPLY_TO)
  @javax.annotation.Nullable
  private CreateCampaignRequestReplyTo replyTo;

  public static final String SERIALIZED_NAME_CC = "cc";
  @SerializedName(SERIALIZED_NAME_CC)
  @javax.annotation.Nullable
  private CreateCampaignRequestReplyTo cc;

  public static final String SERIALIZED_NAME_BCC = "bcc";
  @SerializedName(SERIALIZED_NAME_BCC)
  @javax.annotation.Nullable
  private CreateCampaignRequestReplyTo bcc;

  public static final String SERIALIZED_NAME_SEND_NOW = "sendNow";
  @SerializedName(SERIALIZED_NAME_SEND_NOW)
  @javax.annotation.Nullable
  private Boolean sendNow;

  public static final String SERIALIZED_NAME_SCHEDULED_AT = "scheduledAt";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_AT)
  @javax.annotation.Nullable
  private String scheduledAt;

  public static final String SERIALIZED_NAME_BATCH_SIZE = "batchSize";
  @SerializedName(SERIALIZED_NAME_BATCH_SIZE)
  @javax.annotation.Nullable
  private Integer batchSize;

  public CreateCampaignRequest() {
  }

  public CreateCampaignRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateCampaignRequest from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  public String getFrom() {
    return from;
  }

  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  public CreateCampaignRequest subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nonnull
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public CreateCampaignRequest previewText(@javax.annotation.Nullable String previewText) {
    this.previewText = previewText;
    return this;
  }

  /**
   * Get previewText
   * @return previewText
   */
  @javax.annotation.Nullable
  public String getPreviewText() {
    return previewText;
  }

  public void setPreviewText(@javax.annotation.Nullable String previewText) {
    this.previewText = previewText;
  }


  public CreateCampaignRequest contactBookId(@javax.annotation.Nonnull String contactBookId) {
    this.contactBookId = contactBookId;
    return this;
  }

  /**
   * Get contactBookId
   * @return contactBookId
   */
  @javax.annotation.Nonnull
  public String getContactBookId() {
    return contactBookId;
  }

  public void setContactBookId(@javax.annotation.Nonnull String contactBookId) {
    this.contactBookId = contactBookId;
  }


  public CreateCampaignRequest content(@javax.annotation.Nullable String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  public String getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }


  public CreateCampaignRequest html(@javax.annotation.Nullable String html) {
    this.html = html;
    return this;
  }

  /**
   * Get html
   * @return html
   */
  @javax.annotation.Nullable
  public String getHtml() {
    return html;
  }

  public void setHtml(@javax.annotation.Nullable String html) {
    this.html = html;
  }


  public CreateCampaignRequest replyTo(@javax.annotation.Nullable CreateCampaignRequestReplyTo replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Get replyTo
   * @return replyTo
   */
  @javax.annotation.Nullable
  public CreateCampaignRequestReplyTo getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(@javax.annotation.Nullable CreateCampaignRequestReplyTo replyTo) {
    this.replyTo = replyTo;
  }


  public CreateCampaignRequest cc(@javax.annotation.Nullable CreateCampaignRequestReplyTo cc) {
    this.cc = cc;
    return this;
  }

  /**
   * Get cc
   * @return cc
   */
  @javax.annotation.Nullable
  public CreateCampaignRequestReplyTo getCc() {
    return cc;
  }

  public void setCc(@javax.annotation.Nullable CreateCampaignRequestReplyTo cc) {
    this.cc = cc;
  }


  public CreateCampaignRequest bcc(@javax.annotation.Nullable CreateCampaignRequestReplyTo bcc) {
    this.bcc = bcc;
    return this;
  }

  /**
   * Get bcc
   * @return bcc
   */
  @javax.annotation.Nullable
  public CreateCampaignRequestReplyTo getBcc() {
    return bcc;
  }

  public void setBcc(@javax.annotation.Nullable CreateCampaignRequestReplyTo bcc) {
    this.bcc = bcc;
  }


  public CreateCampaignRequest sendNow(@javax.annotation.Nullable Boolean sendNow) {
    this.sendNow = sendNow;
    return this;
  }

  /**
   * Get sendNow
   * @return sendNow
   */
  @javax.annotation.Nullable
  public Boolean getSendNow() {
    return sendNow;
  }

  public void setSendNow(@javax.annotation.Nullable Boolean sendNow) {
    this.sendNow = sendNow;
  }


  public CreateCampaignRequest scheduledAt(@javax.annotation.Nullable String scheduledAt) {
    this.scheduledAt = scheduledAt;
    return this;
  }

  /**
   * Timestamp in ISO 8601 format or natural language (e.g., &#39;tomorrow 9am&#39;, &#39;next monday 10:30&#39;)
   * @return scheduledAt
   */
  @javax.annotation.Nullable
  public String getScheduledAt() {
    return scheduledAt;
  }

  public void setScheduledAt(@javax.annotation.Nullable String scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  public CreateCampaignRequest batchSize(@javax.annotation.Nullable Integer batchSize) {
    this.batchSize = batchSize;
    return this;
  }

  /**
   * Get batchSize
   * minimum: 1
   * maximum: 100000
   * @return batchSize
   */
  @javax.annotation.Nullable
  public Integer getBatchSize() {
    return batchSize;
  }

  public void setBatchSize(@javax.annotation.Nullable Integer batchSize) {
    this.batchSize = batchSize;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCampaignRequest createCampaignRequest = (CreateCampaignRequest) o;
    return Objects.equals(this.name, createCampaignRequest.name) &&
        Objects.equals(this.from, createCampaignRequest.from) &&
        Objects.equals(this.subject, createCampaignRequest.subject) &&
        Objects.equals(this.previewText, createCampaignRequest.previewText) &&
        Objects.equals(this.contactBookId, createCampaignRequest.contactBookId) &&
        Objects.equals(this.content, createCampaignRequest.content) &&
        Objects.equals(this.html, createCampaignRequest.html) &&
        Objects.equals(this.replyTo, createCampaignRequest.replyTo) &&
        Objects.equals(this.cc, createCampaignRequest.cc) &&
        Objects.equals(this.bcc, createCampaignRequest.bcc) &&
        Objects.equals(this.sendNow, createCampaignRequest.sendNow) &&
        Objects.equals(this.scheduledAt, createCampaignRequest.scheduledAt) &&
        Objects.equals(this.batchSize, createCampaignRequest.batchSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, from, subject, previewText, contactBookId, content, html, replyTo, cc, bcc, sendNow, scheduledAt, batchSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCampaignRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    previewText: ").append(toIndentedString(previewText)).append("\n");
    sb.append("    contactBookId: ").append(toIndentedString(contactBookId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    sendNow: ").append(toIndentedString(sendNow)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("    batchSize: ").append(toIndentedString(batchSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "from", "subject", "previewText", "contactBookId", "content", "html", "replyTo", "cc", "bcc", "sendNow", "scheduledAt", "batchSize"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "from", "subject", "contactBookId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateCampaignRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateCampaignRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateCampaignRequest is not found in the empty JSON string", CreateCampaignRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateCampaignRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateCampaignRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateCampaignRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      if (!jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("previewText") != null && !jsonObj.get("previewText").isJsonNull()) && !jsonObj.get("previewText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `previewText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("previewText").toString()));
      }
      if (!jsonObj.get("contactBookId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contactBookId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactBookId").toString()));
      }
      if ((jsonObj.get("content") != null && !jsonObj.get("content").isJsonNull()) && !jsonObj.get("content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      if ((jsonObj.get("html") != null && !jsonObj.get("html").isJsonNull()) && !jsonObj.get("html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html").toString()));
      }
      // validate the optional field `replyTo`
      if (jsonObj.get("replyTo") != null && !jsonObj.get("replyTo").isJsonNull()) {
        CreateCampaignRequestReplyTo.validateJsonElement(jsonObj.get("replyTo"));
      }
      // validate the optional field `cc`
      if (jsonObj.get("cc") != null && !jsonObj.get("cc").isJsonNull()) {
        CreateCampaignRequestReplyTo.validateJsonElement(jsonObj.get("cc"));
      }
      // validate the optional field `bcc`
      if (jsonObj.get("bcc") != null && !jsonObj.get("bcc").isJsonNull()) {
        CreateCampaignRequestReplyTo.validateJsonElement(jsonObj.get("bcc"));
      }
      if ((jsonObj.get("scheduledAt") != null && !jsonObj.get("scheduledAt").isJsonNull()) && !jsonObj.get("scheduledAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `scheduledAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scheduledAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateCampaignRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateCampaignRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateCampaignRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateCampaignRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateCampaignRequest>() {
           @Override
           public void write(JsonWriter out, CreateCampaignRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateCampaignRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateCampaignRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateCampaignRequest
   * @throws IOException if the JSON string is invalid with respect to CreateCampaignRequest
   */
  public static CreateCampaignRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateCampaignRequest.class);
  }

  /**
   * Convert an instance of CreateCampaignRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

