/*
 * Unsent API
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.unsent.types;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.unsent.JSON;

/**
 * GetContactBook200ResponseDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-07T19:49:52.238598+06:00[Asia/Dhaka]", comments = "Generator version: 7.18.0")
public class GetContactBook200ResponseDetails {
  public static final String SERIALIZED_NAME_TOTAL_CONTACTS = "totalContacts";
  @SerializedName(SERIALIZED_NAME_TOTAL_CONTACTS)
  @javax.annotation.Nonnull
  private BigDecimal totalContacts;

  public static final String SERIALIZED_NAME_UNSUBSCRIBED_CONTACTS = "unsubscribedContacts";
  @SerializedName(SERIALIZED_NAME_UNSUBSCRIBED_CONTACTS)
  @javax.annotation.Nonnull
  private BigDecimal unsubscribedContacts;

  public static final String SERIALIZED_NAME_CAMPAIGNS = "campaigns";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS)
  @javax.annotation.Nonnull
  private List<Object> campaigns = new ArrayList<>();

  public GetContactBook200ResponseDetails() {
  }

  public GetContactBook200ResponseDetails totalContacts(@javax.annotation.Nonnull BigDecimal totalContacts) {
    this.totalContacts = totalContacts;
    return this;
  }

  /**
   * Get totalContacts
   * @return totalContacts
   */
  @javax.annotation.Nonnull
  public BigDecimal getTotalContacts() {
    return totalContacts;
  }

  public void setTotalContacts(@javax.annotation.Nonnull BigDecimal totalContacts) {
    this.totalContacts = totalContacts;
  }


  public GetContactBook200ResponseDetails unsubscribedContacts(@javax.annotation.Nonnull BigDecimal unsubscribedContacts) {
    this.unsubscribedContacts = unsubscribedContacts;
    return this;
  }

  /**
   * Get unsubscribedContacts
   * @return unsubscribedContacts
   */
  @javax.annotation.Nonnull
  public BigDecimal getUnsubscribedContacts() {
    return unsubscribedContacts;
  }

  public void setUnsubscribedContacts(@javax.annotation.Nonnull BigDecimal unsubscribedContacts) {
    this.unsubscribedContacts = unsubscribedContacts;
  }


  public GetContactBook200ResponseDetails campaigns(@javax.annotation.Nonnull List<Object> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  public GetContactBook200ResponseDetails addCampaignsItem(Object campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new ArrayList<>();
    }
    this.campaigns.add(campaignsItem);
    return this;
  }

  /**
   * Get campaigns
   * @return campaigns
   */
  @javax.annotation.Nonnull
  public List<Object> getCampaigns() {
    return campaigns;
  }

  public void setCampaigns(@javax.annotation.Nonnull List<Object> campaigns) {
    this.campaigns = campaigns;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetContactBook200ResponseDetails getContactBook200ResponseDetails = (GetContactBook200ResponseDetails) o;
    return Objects.equals(this.totalContacts, getContactBook200ResponseDetails.totalContacts) &&
        Objects.equals(this.unsubscribedContacts, getContactBook200ResponseDetails.unsubscribedContacts) &&
        Objects.equals(this.campaigns, getContactBook200ResponseDetails.campaigns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalContacts, unsubscribedContacts, campaigns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetContactBook200ResponseDetails {\n");
    sb.append("    totalContacts: ").append(toIndentedString(totalContacts)).append("\n");
    sb.append("    unsubscribedContacts: ").append(toIndentedString(unsubscribedContacts)).append("\n");
    sb.append("    campaigns: ").append(toIndentedString(campaigns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("totalContacts", "unsubscribedContacts", "campaigns"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("totalContacts", "unsubscribedContacts", "campaigns"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetContactBook200ResponseDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetContactBook200ResponseDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetContactBook200ResponseDetails is not found in the empty JSON string", GetContactBook200ResponseDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetContactBook200ResponseDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetContactBook200ResponseDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetContactBook200ResponseDetails.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("campaigns") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("campaigns").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `campaigns` to be an array in the JSON string but got `%s`", jsonObj.get("campaigns").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetContactBook200ResponseDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetContactBook200ResponseDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetContactBook200ResponseDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetContactBook200ResponseDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<GetContactBook200ResponseDetails>() {
           @Override
           public void write(JsonWriter out, GetContactBook200ResponseDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetContactBook200ResponseDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetContactBook200ResponseDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetContactBook200ResponseDetails
   * @throws IOException if the JSON string is invalid with respect to GetContactBook200ResponseDetails
   */
  public static GetContactBook200ResponseDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetContactBook200ResponseDetails.class);
  }

  /**
   * Convert an instance of GetContactBook200ResponseDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

