/*
 * Unsent API
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.unsent.types;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.unsent.types.GetDomains200ResponseInnerDnsRecordsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.unsent.JSON;

/**
 * GetDomains200ResponseInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-07T19:49:52.238598+06:00[Asia/Dhaka]", comments = "Generator version: 7.18.0")
public class GetDomains200ResponseInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_TEAM_ID = "teamId";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  @javax.annotation.Nonnull
  private String teamId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @javax.annotation.Nullable
  private String region = "us-east-1";

  public static final String SERIALIZED_NAME_CLICK_TRACKING = "clickTracking";
  @SerializedName(SERIALIZED_NAME_CLICK_TRACKING)
  @javax.annotation.Nullable
  private Boolean clickTracking = false;

  public static final String SERIALIZED_NAME_OPEN_TRACKING = "openTracking";
  @SerializedName(SERIALIZED_NAME_OPEN_TRACKING)
  @javax.annotation.Nullable
  private Boolean openTracking = false;

  public static final String SERIALIZED_NAME_PUBLIC_KEY = "publicKey";
  @SerializedName(SERIALIZED_NAME_PUBLIC_KEY)
  @javax.annotation.Nonnull
  private String publicKey;

  public static final String SERIALIZED_NAME_DKIM_STATUS = "dkimStatus";
  @SerializedName(SERIALIZED_NAME_DKIM_STATUS)
  @javax.annotation.Nullable
  private String dkimStatus;

  public static final String SERIALIZED_NAME_SPF_DETAILS = "spfDetails";
  @SerializedName(SERIALIZED_NAME_SPF_DETAILS)
  @javax.annotation.Nullable
  private String spfDetails;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private String updatedAt;

  public static final String SERIALIZED_NAME_DMARC_ADDED = "dmarcAdded";
  @SerializedName(SERIALIZED_NAME_DMARC_ADDED)
  @javax.annotation.Nullable
  private Boolean dmarcAdded = false;

  public static final String SERIALIZED_NAME_IS_VERIFYING = "isVerifying";
  @SerializedName(SERIALIZED_NAME_IS_VERIFYING)
  @javax.annotation.Nullable
  private Boolean isVerifying = false;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "errorMessage";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  @javax.annotation.Nullable
  private String errorMessage;

  public static final String SERIALIZED_NAME_SUBDOMAIN = "subdomain";
  @SerializedName(SERIALIZED_NAME_SUBDOMAIN)
  @javax.annotation.Nullable
  private String subdomain;

  public static final String SERIALIZED_NAME_VERIFICATION_ERROR = "verificationError";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_ERROR)
  @javax.annotation.Nullable
  private String verificationError;

  public static final String SERIALIZED_NAME_LAST_CHECKED_TIME = "lastCheckedTime";
  @SerializedName(SERIALIZED_NAME_LAST_CHECKED_TIME)
  @javax.annotation.Nullable
  private String lastCheckedTime;

  public static final String SERIALIZED_NAME_DNS_RECORDS = "dnsRecords";
  @SerializedName(SERIALIZED_NAME_DNS_RECORDS)
  @javax.annotation.Nonnull
  private List<GetDomains200ResponseInnerDnsRecordsInner> dnsRecords = new ArrayList<>();

  public GetDomains200ResponseInner() {
  }

  public GetDomains200ResponseInner id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the domain
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetDomains200ResponseInner name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the domain
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public GetDomains200ResponseInner teamId(@javax.annotation.Nonnull String teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * The ID of the team
   * @return teamId
   */
  @javax.annotation.Nonnull
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(@javax.annotation.Nonnull String teamId) {
    this.teamId = teamId;
  }


  public GetDomains200ResponseInner status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the domain
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public GetDomains200ResponseInner region(@javax.annotation.Nullable String region) {
    this.region = region;
    return this;
  }

  /**
   * The region of the domain
   * @return region
   */
  @javax.annotation.Nullable
  public String getRegion() {
    return region;
  }

  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = region;
  }


  public GetDomains200ResponseInner clickTracking(@javax.annotation.Nullable Boolean clickTracking) {
    this.clickTracking = clickTracking;
    return this;
  }

  /**
   * Whether click tracking is enabled
   * @return clickTracking
   */
  @javax.annotation.Nullable
  public Boolean getClickTracking() {
    return clickTracking;
  }

  public void setClickTracking(@javax.annotation.Nullable Boolean clickTracking) {
    this.clickTracking = clickTracking;
  }


  public GetDomains200ResponseInner openTracking(@javax.annotation.Nullable Boolean openTracking) {
    this.openTracking = openTracking;
    return this;
  }

  /**
   * Whether open tracking is enabled
   * @return openTracking
   */
  @javax.annotation.Nullable
  public Boolean getOpenTracking() {
    return openTracking;
  }

  public void setOpenTracking(@javax.annotation.Nullable Boolean openTracking) {
    this.openTracking = openTracking;
  }


  public GetDomains200ResponseInner publicKey(@javax.annotation.Nonnull String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

  /**
   * The public key of the domain
   * @return publicKey
   */
  @javax.annotation.Nonnull
  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(@javax.annotation.Nonnull String publicKey) {
    this.publicKey = publicKey;
  }


  public GetDomains200ResponseInner dkimStatus(@javax.annotation.Nullable String dkimStatus) {
    this.dkimStatus = dkimStatus;
    return this;
  }

  /**
   * The DKIM status of the domain
   * @return dkimStatus
   */
  @javax.annotation.Nullable
  public String getDkimStatus() {
    return dkimStatus;
  }

  public void setDkimStatus(@javax.annotation.Nullable String dkimStatus) {
    this.dkimStatus = dkimStatus;
  }


  public GetDomains200ResponseInner spfDetails(@javax.annotation.Nullable String spfDetails) {
    this.spfDetails = spfDetails;
    return this;
  }

  /**
   * The SPF details of the domain
   * @return spfDetails
   */
  @javax.annotation.Nullable
  public String getSpfDetails() {
    return spfDetails;
  }

  public void setSpfDetails(@javax.annotation.Nullable String spfDetails) {
    this.spfDetails = spfDetails;
  }


  public GetDomains200ResponseInner createdAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The creation date of the domain
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public GetDomains200ResponseInner updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The last update date of the domain
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public GetDomains200ResponseInner dmarcAdded(@javax.annotation.Nullable Boolean dmarcAdded) {
    this.dmarcAdded = dmarcAdded;
    return this;
  }

  /**
   * Whether DMARC is added
   * @return dmarcAdded
   */
  @javax.annotation.Nullable
  public Boolean getDmarcAdded() {
    return dmarcAdded;
  }

  public void setDmarcAdded(@javax.annotation.Nullable Boolean dmarcAdded) {
    this.dmarcAdded = dmarcAdded;
  }


  public GetDomains200ResponseInner isVerifying(@javax.annotation.Nullable Boolean isVerifying) {
    this.isVerifying = isVerifying;
    return this;
  }

  /**
   * Whether the domain is verifying
   * @return isVerifying
   */
  @javax.annotation.Nullable
  public Boolean getIsVerifying() {
    return isVerifying;
  }

  public void setIsVerifying(@javax.annotation.Nullable Boolean isVerifying) {
    this.isVerifying = isVerifying;
  }


  public GetDomains200ResponseInner errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * The error message of the domain
   * @return errorMessage
   */
  @javax.annotation.Nullable
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public GetDomains200ResponseInner subdomain(@javax.annotation.Nullable String subdomain) {
    this.subdomain = subdomain;
    return this;
  }

  /**
   * The subdomain of the domain
   * @return subdomain
   */
  @javax.annotation.Nullable
  public String getSubdomain() {
    return subdomain;
  }

  public void setSubdomain(@javax.annotation.Nullable String subdomain) {
    this.subdomain = subdomain;
  }


  public GetDomains200ResponseInner verificationError(@javax.annotation.Nullable String verificationError) {
    this.verificationError = verificationError;
    return this;
  }

  /**
   * The verification error of the domain
   * @return verificationError
   */
  @javax.annotation.Nullable
  public String getVerificationError() {
    return verificationError;
  }

  public void setVerificationError(@javax.annotation.Nullable String verificationError) {
    this.verificationError = verificationError;
  }


  public GetDomains200ResponseInner lastCheckedTime(@javax.annotation.Nullable String lastCheckedTime) {
    this.lastCheckedTime = lastCheckedTime;
    return this;
  }

  /**
   * The last checked time of the domain
   * @return lastCheckedTime
   */
  @javax.annotation.Nullable
  public String getLastCheckedTime() {
    return lastCheckedTime;
  }

  public void setLastCheckedTime(@javax.annotation.Nullable String lastCheckedTime) {
    this.lastCheckedTime = lastCheckedTime;
  }


  public GetDomains200ResponseInner dnsRecords(@javax.annotation.Nonnull List<GetDomains200ResponseInnerDnsRecordsInner> dnsRecords) {
    this.dnsRecords = dnsRecords;
    return this;
  }

  public GetDomains200ResponseInner addDnsRecordsItem(GetDomains200ResponseInnerDnsRecordsInner dnsRecordsItem) {
    if (this.dnsRecords == null) {
      this.dnsRecords = new ArrayList<>();
    }
    this.dnsRecords.add(dnsRecordsItem);
    return this;
  }

  /**
   * The DNS records of the domain
   * @return dnsRecords
   */
  @javax.annotation.Nonnull
  public List<GetDomains200ResponseInnerDnsRecordsInner> getDnsRecords() {
    return dnsRecords;
  }

  public void setDnsRecords(@javax.annotation.Nonnull List<GetDomains200ResponseInnerDnsRecordsInner> dnsRecords) {
    this.dnsRecords = dnsRecords;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDomains200ResponseInner getDomains200ResponseInner = (GetDomains200ResponseInner) o;
    return Objects.equals(this.id, getDomains200ResponseInner.id) &&
        Objects.equals(this.name, getDomains200ResponseInner.name) &&
        Objects.equals(this.teamId, getDomains200ResponseInner.teamId) &&
        Objects.equals(this.status, getDomains200ResponseInner.status) &&
        Objects.equals(this.region, getDomains200ResponseInner.region) &&
        Objects.equals(this.clickTracking, getDomains200ResponseInner.clickTracking) &&
        Objects.equals(this.openTracking, getDomains200ResponseInner.openTracking) &&
        Objects.equals(this.publicKey, getDomains200ResponseInner.publicKey) &&
        Objects.equals(this.dkimStatus, getDomains200ResponseInner.dkimStatus) &&
        Objects.equals(this.spfDetails, getDomains200ResponseInner.spfDetails) &&
        Objects.equals(this.createdAt, getDomains200ResponseInner.createdAt) &&
        Objects.equals(this.updatedAt, getDomains200ResponseInner.updatedAt) &&
        Objects.equals(this.dmarcAdded, getDomains200ResponseInner.dmarcAdded) &&
        Objects.equals(this.isVerifying, getDomains200ResponseInner.isVerifying) &&
        Objects.equals(this.errorMessage, getDomains200ResponseInner.errorMessage) &&
        Objects.equals(this.subdomain, getDomains200ResponseInner.subdomain) &&
        Objects.equals(this.verificationError, getDomains200ResponseInner.verificationError) &&
        Objects.equals(this.lastCheckedTime, getDomains200ResponseInner.lastCheckedTime) &&
        Objects.equals(this.dnsRecords, getDomains200ResponseInner.dnsRecords);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, teamId, status, region, clickTracking, openTracking, publicKey, dkimStatus, spfDetails, createdAt, updatedAt, dmarcAdded, isVerifying, errorMessage, subdomain, verificationError, lastCheckedTime, dnsRecords);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDomains200ResponseInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    clickTracking: ").append(toIndentedString(clickTracking)).append("\n");
    sb.append("    openTracking: ").append(toIndentedString(openTracking)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    dkimStatus: ").append(toIndentedString(dkimStatus)).append("\n");
    sb.append("    spfDetails: ").append(toIndentedString(spfDetails)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    dmarcAdded: ").append(toIndentedString(dmarcAdded)).append("\n");
    sb.append("    isVerifying: ").append(toIndentedString(isVerifying)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    subdomain: ").append(toIndentedString(subdomain)).append("\n");
    sb.append("    verificationError: ").append(toIndentedString(verificationError)).append("\n");
    sb.append("    lastCheckedTime: ").append(toIndentedString(lastCheckedTime)).append("\n");
    sb.append("    dnsRecords: ").append(toIndentedString(dnsRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "teamId", "status", "region", "clickTracking", "openTracking", "publicKey", "dkimStatus", "spfDetails", "createdAt", "updatedAt", "dmarcAdded", "isVerifying", "errorMessage", "subdomain", "verificationError", "lastCheckedTime", "dnsRecords"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "teamId", "status", "publicKey", "createdAt", "updatedAt", "dnsRecords"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetDomains200ResponseInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetDomains200ResponseInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetDomains200ResponseInner is not found in the empty JSON string", GetDomains200ResponseInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetDomains200ResponseInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetDomains200ResponseInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetDomains200ResponseInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("teamId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `teamId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("teamId").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
      if (!jsonObj.get("publicKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `publicKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("publicKey").toString()));
      }
      if ((jsonObj.get("dkimStatus") != null && !jsonObj.get("dkimStatus").isJsonNull()) && !jsonObj.get("dkimStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dkimStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dkimStatus").toString()));
      }
      if ((jsonObj.get("spfDetails") != null && !jsonObj.get("spfDetails").isJsonNull()) && !jsonObj.get("spfDetails").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `spfDetails` to be a primitive type in the JSON string but got `%s`", jsonObj.get("spfDetails").toString()));
      }
      if (!jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if (!jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if ((jsonObj.get("errorMessage") != null && !jsonObj.get("errorMessage").isJsonNull()) && !jsonObj.get("errorMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `errorMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorMessage").toString()));
      }
      if ((jsonObj.get("subdomain") != null && !jsonObj.get("subdomain").isJsonNull()) && !jsonObj.get("subdomain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subdomain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subdomain").toString()));
      }
      if ((jsonObj.get("verificationError") != null && !jsonObj.get("verificationError").isJsonNull()) && !jsonObj.get("verificationError").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `verificationError` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verificationError").toString()));
      }
      if ((jsonObj.get("lastCheckedTime") != null && !jsonObj.get("lastCheckedTime").isJsonNull()) && !jsonObj.get("lastCheckedTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `lastCheckedTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastCheckedTime").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("dnsRecords").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dnsRecords` to be an array in the JSON string but got `%s`", jsonObj.get("dnsRecords").toString()));
      }

      JsonArray jsonArraydnsRecords = jsonObj.getAsJsonArray("dnsRecords");
      // validate the required field `dnsRecords` (array)
      for (int i = 0; i < jsonArraydnsRecords.size(); i++) {
        GetDomains200ResponseInnerDnsRecordsInner.validateJsonElement(jsonArraydnsRecords.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetDomains200ResponseInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetDomains200ResponseInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetDomains200ResponseInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetDomains200ResponseInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetDomains200ResponseInner>() {
           @Override
           public void write(JsonWriter out, GetDomains200ResponseInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetDomains200ResponseInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetDomains200ResponseInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetDomains200ResponseInner
   * @throws IOException if the JSON string is invalid with respect to GetDomains200ResponseInner
   */
  public static GetDomains200ResponseInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetDomains200ResponseInner.class);
  }

  /**
   * Convert an instance of GetDomains200ResponseInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

