/*
 * Unsent API
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.unsent.types;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.unsent.types.SendEmailRequestTo;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.unsent.JSON;

/**
 * SendEmailRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-07T19:49:52.238598+06:00[Asia/Dhaka]", comments = "Generator version: 7.18.0")
public class SendEmailRequest {
  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  @javax.annotation.Nonnull
  private SendEmailRequestTo to;

  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  @javax.annotation.Nonnull
  private String from;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nullable
  private String subject;

  public static final String SERIALIZED_NAME_TEMPLATE_ID = "templateId";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_ID)
  @javax.annotation.Nullable
  private String templateId;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  @javax.annotation.Nullable
  private Map<String, String> variables = new HashMap<>();

  public static final String SERIALIZED_NAME_REPLY_TO = "replyTo";
  @SerializedName(SERIALIZED_NAME_REPLY_TO)
  @javax.annotation.Nullable
  private SendEmailRequestTo replyTo;

  public static final String SERIALIZED_NAME_CC = "cc";
  @SerializedName(SERIALIZED_NAME_CC)
  @javax.annotation.Nullable
  private SendEmailRequestTo cc;

  public static final String SERIALIZED_NAME_BCC = "bcc";
  @SerializedName(SERIALIZED_NAME_BCC)
  @javax.annotation.Nullable
  private SendEmailRequestTo bcc;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nullable
  private String html;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  @javax.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String SERIALIZED_NAME_ATTACHMENTS = "attachments";
  @SerializedName(SERIALIZED_NAME_ATTACHMENTS)
  @javax.annotation.Nullable
  private List<Object> attachments = new ArrayList<>();

  public static final String SERIALIZED_NAME_SCHEDULED_AT = "scheduledAt";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime scheduledAt;

  public static final String SERIALIZED_NAME_IN_REPLY_TO_ID = "inReplyToId";
  @SerializedName(SERIALIZED_NAME_IN_REPLY_TO_ID)
  @javax.annotation.Nullable
  private String inReplyToId;

  public SendEmailRequest() {
  }

  public SendEmailRequest to(@javax.annotation.Nonnull SendEmailRequestTo to) {
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @javax.annotation.Nonnull
  public SendEmailRequestTo getTo() {
    return to;
  }

  public void setTo(@javax.annotation.Nonnull SendEmailRequestTo to) {
    this.to = to;
  }


  public SendEmailRequest from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  public String getFrom() {
    return from;
  }

  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  public SendEmailRequest subject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Optional when templateId is provided
   * @return subject
   */
  @javax.annotation.Nullable
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
  }


  public SendEmailRequest templateId(@javax.annotation.Nullable String templateId) {
    this.templateId = templateId;
    return this;
  }

  /**
   * ID of a template from the dashboard
   * @return templateId
   */
  @javax.annotation.Nullable
  public String getTemplateId() {
    return templateId;
  }

  public void setTemplateId(@javax.annotation.Nullable String templateId) {
    this.templateId = templateId;
  }


  public SendEmailRequest variables(@javax.annotation.Nullable Map<String, String> variables) {
    this.variables = variables;
    return this;
  }

  public SendEmailRequest putVariablesItem(String key, String variablesItem) {
    if (this.variables == null) {
      this.variables = new HashMap<>();
    }
    this.variables.put(key, variablesItem);
    return this;
  }

  /**
   * Get variables
   * @return variables
   */
  @javax.annotation.Nullable
  public Map<String, String> getVariables() {
    return variables;
  }

  public void setVariables(@javax.annotation.Nullable Map<String, String> variables) {
    this.variables = variables;
  }


  public SendEmailRequest replyTo(@javax.annotation.Nullable SendEmailRequestTo replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Get replyTo
   * @return replyTo
   */
  @javax.annotation.Nullable
  public SendEmailRequestTo getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(@javax.annotation.Nullable SendEmailRequestTo replyTo) {
    this.replyTo = replyTo;
  }


  public SendEmailRequest cc(@javax.annotation.Nullable SendEmailRequestTo cc) {
    this.cc = cc;
    return this;
  }

  /**
   * Get cc
   * @return cc
   */
  @javax.annotation.Nullable
  public SendEmailRequestTo getCc() {
    return cc;
  }

  public void setCc(@javax.annotation.Nullable SendEmailRequestTo cc) {
    this.cc = cc;
  }


  public SendEmailRequest bcc(@javax.annotation.Nullable SendEmailRequestTo bcc) {
    this.bcc = bcc;
    return this;
  }

  /**
   * Get bcc
   * @return bcc
   */
  @javax.annotation.Nullable
  public SendEmailRequestTo getBcc() {
    return bcc;
  }

  public void setBcc(@javax.annotation.Nullable SendEmailRequestTo bcc) {
    this.bcc = bcc;
  }


  public SendEmailRequest text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public SendEmailRequest html(@javax.annotation.Nullable String html) {
    this.html = html;
    return this;
  }

  /**
   * Get html
   * @return html
   */
  @javax.annotation.Nullable
  public String getHtml() {
    return html;
  }

  public void setHtml(@javax.annotation.Nullable String html) {
    this.html = html;
  }


  public SendEmailRequest headers(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public SendEmailRequest putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Custom headers to included with the emails
   * @return headers
   */
  @javax.annotation.Nullable
  public Map<String, String> getHeaders() {
    return headers;
  }

  public void setHeaders(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }


  public SendEmailRequest attachments(@javax.annotation.Nullable List<Object> attachments) {
    this.attachments = attachments;
    return this;
  }

  public SendEmailRequest addAttachmentsItem(Object attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

  /**
   * Get attachments
   * @return attachments
   */
  @javax.annotation.Nullable
  public List<Object> getAttachments() {
    return attachments;
  }

  public void setAttachments(@javax.annotation.Nullable List<Object> attachments) {
    this.attachments = attachments;
  }


  public SendEmailRequest scheduledAt(@javax.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
    return this;
  }

  /**
   * Get scheduledAt
   * @return scheduledAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getScheduledAt() {
    return scheduledAt;
  }

  public void setScheduledAt(@javax.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  public SendEmailRequest inReplyToId(@javax.annotation.Nullable String inReplyToId) {
    this.inReplyToId = inReplyToId;
    return this;
  }

  /**
   * Get inReplyToId
   * @return inReplyToId
   */
  @javax.annotation.Nullable
  public String getInReplyToId() {
    return inReplyToId;
  }

  public void setInReplyToId(@javax.annotation.Nullable String inReplyToId) {
    this.inReplyToId = inReplyToId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendEmailRequest sendEmailRequest = (SendEmailRequest) o;
    return Objects.equals(this.to, sendEmailRequest.to) &&
        Objects.equals(this.from, sendEmailRequest.from) &&
        Objects.equals(this.subject, sendEmailRequest.subject) &&
        Objects.equals(this.templateId, sendEmailRequest.templateId) &&
        Objects.equals(this.variables, sendEmailRequest.variables) &&
        Objects.equals(this.replyTo, sendEmailRequest.replyTo) &&
        Objects.equals(this.cc, sendEmailRequest.cc) &&
        Objects.equals(this.bcc, sendEmailRequest.bcc) &&
        Objects.equals(this.text, sendEmailRequest.text) &&
        Objects.equals(this.html, sendEmailRequest.html) &&
        Objects.equals(this.headers, sendEmailRequest.headers) &&
        Objects.equals(this.attachments, sendEmailRequest.attachments) &&
        Objects.equals(this.scheduledAt, sendEmailRequest.scheduledAt) &&
        Objects.equals(this.inReplyToId, sendEmailRequest.inReplyToId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, from, subject, templateId, variables, replyTo, cc, bcc, text, html, headers, attachments, scheduledAt, inReplyToId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendEmailRequest {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("    inReplyToId: ").append(toIndentedString(inReplyToId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("to", "from", "subject", "templateId", "variables", "replyTo", "cc", "bcc", "text", "html", "headers", "attachments", "scheduledAt", "inReplyToId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("to", "from"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SendEmailRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SendEmailRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SendEmailRequest is not found in the empty JSON string", SendEmailRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SendEmailRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SendEmailRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SendEmailRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `to`
      SendEmailRequestTo.validateJsonElement(jsonObj.get("to"));
      if (!jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      if ((jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull()) && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("templateId") != null && !jsonObj.get("templateId").isJsonNull()) && !jsonObj.get("templateId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `templateId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateId").toString()));
      }
      // validate the optional field `replyTo`
      if (jsonObj.get("replyTo") != null && !jsonObj.get("replyTo").isJsonNull()) {
        SendEmailRequestTo.validateJsonElement(jsonObj.get("replyTo"));
      }
      // validate the optional field `cc`
      if (jsonObj.get("cc") != null && !jsonObj.get("cc").isJsonNull()) {
        SendEmailRequestTo.validateJsonElement(jsonObj.get("cc"));
      }
      // validate the optional field `bcc`
      if (jsonObj.get("bcc") != null && !jsonObj.get("bcc").isJsonNull()) {
        SendEmailRequestTo.validateJsonElement(jsonObj.get("bcc"));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      if ((jsonObj.get("html") != null && !jsonObj.get("html").isJsonNull()) && !jsonObj.get("html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("attachments") != null && !jsonObj.get("attachments").isJsonNull() && !jsonObj.get("attachments").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `attachments` to be an array in the JSON string but got `%s`", jsonObj.get("attachments").toString()));
      }
      if ((jsonObj.get("inReplyToId") != null && !jsonObj.get("inReplyToId").isJsonNull()) && !jsonObj.get("inReplyToId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inReplyToId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inReplyToId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SendEmailRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SendEmailRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SendEmailRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SendEmailRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SendEmailRequest>() {
           @Override
           public void write(JsonWriter out, SendEmailRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SendEmailRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SendEmailRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SendEmailRequest
   * @throws IOException if the JSON string is invalid with respect to SendEmailRequest
   */
  public static SendEmailRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SendEmailRequest.class);
  }

  /**
   * Convert an instance of SendEmailRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

